version: '3.9'

services:

  db:
    image: postgres
    container_name: tz_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: orders
#    ports:
#      - 54321:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  kanalservis:
    container_name: kanalservis
    build: .
    restart: always
    environment:
      TZ: ${TZ}
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
      SPREADSHEETS_ID: ${SPREADSHEETS_ID}
    ports:
      - 8083:8000

#  nginx:
#    container_name: nginx_kanalservis
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    depends_on:
#      - kanalservis
#    restart: always
#    environment:
#      - "TZ=Europe/Moscow"
#    ports:
#      - 8083:81